# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: DeepSensor
author: Tom Andersson
logo: ../figs/DeepSensorLogo2.png
email: tomandersson3@gmail.com

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off  # Don't run notebooks during doc compilation
#  execute_notebooks: force
#  timeout: 1200  # 20 mins
#  # Exclude notebooks with model training
#  exclude_patterns:
#    - "*quickstart*"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: deepsensor.tex
    
only_build_toc_files: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/tom-andersson/deepsensor  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.viewcode'
  config:
    add_module_names: False
    autodoc_typehints: "none"
    autoclass_content: "class"
    intersphinx_mapping:
      python:
        - https://docs.python.org/3
        - null
      pandas:
        - http://pandas.pydata.org/pandas-docs/stable/
        - null
      # tensorflow:
      #  - http://www.tensorflow.org/api_docs/python
      #  - https://raw.githubusercontent.com/GPflow/tensorflow-intersphinx/master/tf2_py_objects.inv
      numpy:
        - https://numpy.org/doc/stable/
        - null
      matplotlib:
        - http://matplotlib.org/stable/
        - null
      xarray:
        - http://xarray.pydata.org/en/stable/
        - https://docs.xarray.dev/en/stable/objects.inv
    language: en
    copybutton_prompt_text: "$"