name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - uses: nikeee/setup-pandoc@v1
            - name: "Install dependencies"
              run: pip install -r requirements.txt
            - name: Install GEOS for cartopy (https://scitools.org.uk/cartopy/docs/latest/installing.html#required-dependencies)
              run: sudo apt-get install libgeos-dev
            - name: Pip install cartopy for testing plotting
              run: pip install cartopy
            - name: "Install jupyterbook"
              run: pip install -r requirements.docs.txt
            - name: "Run jupyterbook"
              run: jupyter-book build docs --all
            - name: "Deploy"
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/docs') }}
              with:
                    publish_branch: gh-pages
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: docs/_build/html/
                    force_orphan: true
