name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install GEOS for cartopy (https://scitools.org.uk/cartopy/docs/latest/installing.html#required-dependencies)
      run: |
        if [ ${{ matrix.os }} == 'ubuntu-20.04' ]; then
          sudo apt-get install libgeos-dev
        elif [ ${{ matrix.os }} == 'macos-latest' ]; then
          brew install geos
        fi
    - name: Pip install cartopy for testing plotting
      run: |
        pip install cartopy
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt
    - name: Test with tox
      run: tox
    - name: Run coveralls
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
        COVERALLS_PARALLEL: true


  finish:
    name: Finish Coveralls
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - name: Finish Coveralls
      uses: coverallsapp/github-action@v1
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true